# Generated by Django 3.0.2 on 2020-03-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgMD5', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'img',
                'ordering': ['-id'],
            },
        ),
    ]
