# Generated by Django 2.2.5 on 2020-03-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_auto_20200310_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vercode',
            old_name='createTime',
            new_name='time',
        ),
    ]
