# Generated by Django 2.2.5 on 2020-03-10 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coder', '0003_auto_20200310_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='users',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coder.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Answer',
                'ordering': ['-id'],
            },
        ),
    ]
